# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ed216a04788c893728548939a82d07e78c8a79a03ee169a65887d41f050e624dfa1aa7c1baf077406d381bbc882c40e8af3a7633d43102600e8c30ab5faac37

test:
  secret_key_base: f989da6c645c184c564ff52f28832e7791d27380de952b4386c912345d97486a30337da7de59a095b4a4837f7cde9c4a85d62b83b70579176a1c8069aa938f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
